
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    // Lista para almacenar los clientes registrados
    private ListaClientes listaClientes;
    private ListaPeliculas listaPeliculas;
    private ListaReservas listaReservas;

    public Interfaz() {
        initComponents();

        listaClientes = new ListaClientes();
        listaPeliculas = new ListaPeliculas();
        listaReservas = new ListaReservas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnRegistrarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        btnAgregarPeliculas = new javax.swing.JButton();
        btnModificarPelicula = new javax.swing.JButton();
        btnEliminarPelicula = new javax.swing.JButton();
        btnVerCartelera = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        btnRealizarReserva = new javax.swing.JButton();
        btnVerReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sistema de Boleteria ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cinepilis");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boleto.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boleto.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/letra-c.png"))); // NOI18N

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.setFocusable(false);
        btnRegistrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistrarCliente);

        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.setFocusable(false);
        btnEliminarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminarCliente);

        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        btnAgregarPeliculas.setText("Agregar Pelicula");
        btnAgregarPeliculas.setFocusable(false);
        btnAgregarPeliculas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarPeliculas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculasActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAgregarPeliculas);

        btnModificarPelicula.setText("Modificar Pelicula");
        btnModificarPelicula.setFocusable(false);
        btnModificarPelicula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarPelicula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPeliculaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnModificarPelicula);

        btnEliminarPelicula.setText("Eliminar Pelicula");
        btnEliminarPelicula.setFocusable(false);
        btnEliminarPelicula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarPelicula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPeliculaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnEliminarPelicula);

        btnVerCartelera.setText("Ver Cartelera");
        btnVerCartelera.setFocusable(false);
        btnVerCartelera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerCartelera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCarteleraActionPerformed(evt);
            }
        });
        jToolBar2.add(btnVerCartelera);

        jToolBar3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar3.setRollover(true);

        btnRealizarReserva.setText("Realizar Reserva");
        btnRealizarReserva.setFocusable(false);
        btnRealizarReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRealizarReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarReservaActionPerformed(evt);
            }
        });
        jToolBar3.add(btnRealizarReserva);

        btnVerReserva.setText("Ver Reservas");
        btnVerReserva.setFocusable(false);
        btnVerReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReservaActionPerformed(evt);
            }
        });
        jToolBar3.add(btnVerReserva);

        btnCancelarReserva.setText("Cancelar Reserva");
        btnCancelarReserva.setFocusable(false);
        btnCancelarReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservaActionPerformed(evt);
            }
        });
        jToolBar3.add(btnCancelarReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(214, 214, 214))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 118, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed

        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del cliente:");
        String cedula = JOptionPane.showInputDialog(this, "Ingrese la cédula del cliente:");

        if (nombre != null && cedula != null) {
            Cliente nuevoCliente = new Cliente(nombre, cedula);
            listaClientes.agregarCliente(nuevoCliente);
            JOptionPane.showMessageDialog(this, "Cliente registrado con éxito.");
        }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnVerCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCarteleraActionPerformed
        String cartelera = listaPeliculas.obtenerLista();
        JOptionPane.showMessageDialog(this, cartelera.isEmpty() ? "No hay películas en cartelera." : cartelera);
    }//GEN-LAST:event_btnVerCarteleraActionPerformed

    private void btnRealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarReservaActionPerformed

       

    }//GEN-LAST:event_btnRealizarReservaActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed

        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del cliente a eliminar:");
        if (listaClientes.eliminarCliente(nombre)) {
            JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del cliente con la reserva:");
        if (listaReservas.eliminarReserva(nombre)) {
            JOptionPane.showMessageDialog(this, "Reserva cancelada correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la reserva.");
        }
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    private void btnVerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReservaActionPerformed
        String reservas = listaReservas.obtenerLista();
        JOptionPane.showMessageDialog(this, reservas.isEmpty() ? "No hay reservas registradas." : reservas);
    }//GEN-LAST:event_btnVerReservaActionPerformed

    private void btnAgregarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculasActionPerformed
        String titulo = JOptionPane.showInputDialog(this, "Ingrese el título de la película:");
        String genero = JOptionPane.showInputDialog(this, "Ingrese el género de la película:");
        String duracionStr = JOptionPane.showInputDialog(this, "Ingrese la duración en minutos:");
        String clasificacion = JOptionPane.showInputDialog(this, "Ingrese la clasificación (Ejemplo: PG-13, R, G):");

        if (titulo != null && genero != null && duracionStr != null && clasificacion != null) {
            try {
                int duracion = Integer.parseInt(duracionStr); // Convertimos la duración a número
                Pelicula nuevaPelicula = new Pelicula(titulo, genero, duracion, clasificacion);
                listaPeliculas.agregarPelicula(nuevaPelicula);
                JOptionPane.showMessageDialog(this, "Película agregada con éxito.");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error: La duración debe ser un número.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
        }
    }//GEN-LAST:event_btnAgregarPeliculasActionPerformed

    private void btnEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPeliculaActionPerformed

        String titulo = JOptionPane.showInputDialog(this, "Ingrese el título de la película a eliminar:");

        if (titulo != null && !titulo.trim().isEmpty()) {
            boolean eliminada = listaPeliculas.eliminarPelicula(titulo);
            if (eliminada) {
                JOptionPane.showMessageDialog(this, "Película eliminada con éxito.");
            } else {
                JOptionPane.showMessageDialog(this, "Película no encontrada.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un título válido.");
        }


    }//GEN-LAST:event_btnEliminarPeliculaActionPerformed

    private void btnModificarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPeliculaActionPerformed
        String titulo = JOptionPane.showInputDialog(this, "Ingrese el título de la película a modificar:");

        Pelicula pelicula = listaPeliculas.buscarPelicula(titulo);
        if (pelicula != null) {
            String nuevoTitulo = JOptionPane.showInputDialog(this, "Nuevo título:", pelicula.getTitulo());
            String nuevoGenero = JOptionPane.showInputDialog(this, "Nuevo género:", pelicula.getGenero());
            String nuevaDuracionStr = JOptionPane.showInputDialog(this, "Nueva duración (minutos):", pelicula.getDuracion());
            String nuevaClasificacion = JOptionPane.showInputDialog(this, "Nueva clasificación:", pelicula.getClasificacion());

            try {
                int nuevaDuracion = Integer.parseInt(nuevaDuracionStr);
                pelicula.setTitulo(nuevoTitulo);
                pelicula.setGenero(nuevoGenero);
                pelicula.setDuracion(nuevaDuracion);
                pelicula.setClasificacion(nuevaClasificacion);
                JOptionPane.showMessageDialog(this, "Película modificada con éxito.");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error: La duración debe ser un número.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Película no encontrada.");
        }
    }//GEN-LAST:event_btnModificarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPeliculas;
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarPelicula;
    private javax.swing.JButton btnModificarPelicula;
    private javax.swing.JButton btnRealizarReserva;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnVerCartelera;
    private javax.swing.JButton btnVerReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
